### PR TITLE
WDP181202-6

### PR DESCRIPTION
**Pull request by damianmichalski**
Dodanie w index.html starej ceny oraz dodanie styli.

### CODE REVIEW

**Comment by pawel-schmidt** [comment]
BTW code formatting caused conflicts.

**Comment by damianmichalski** [comment]
@pawel-schmidt  should I revert this automatically formatted code? Or we are merging it as it is right now?

**Comment by pawel-schmidt** [comment]
@damianmichalski we cannot merge it until there are merge conflicts. You need to resolve them first. The fastest way, in my opinion, will be bringing back `index.html` file from `master` branch using `git checkout master src/index.html` command (while being on your `WDP181202-6` branch) and add again a couple of `old-price`s.

**Comment by damianmichalski** [comment]
@pawel-schmidt changes has been pushed.

**Comment by damianmichalski** [comment]
@pawel-schmidt  or @xkxd  can you check my last changes? Is everything good now? My code editor is adding some new line on automat formating, thats the reasone why there are some many changes.

**Pull request merged**
